#!/bin/sh
#

echo "1. Building docs"

cd src

python3 human_readable_json.py

echo "--> Files built"

cd ..

git add docs/jsonBrowser/*.md

echo "--> Files added to to the index, please commit them"

cd src

echo "2. Linting schema files"

python3 schema_linter.py

echo "Schema files are linted"
