version: 3

# The following line breaks the yml - 404 page not found error
# extends: https://api.github.com/repos/example/pullapprove-config/contents/.pullapprove.yml

pullapprove_conditions:
- condition: "base.ref == 'develop'"
  unmet_status: "failure"
  explanation: "Review not required unless merging to develop"
- condition: "'on hold' not in labels"
  unmet_status: "pending"
  explanation: "PR review is on hold"
- condition: "'*travis*' in statuses.successful"
  unmet_status: "failure"
  explanation: "Travis CI tests must pass before review starts"
# TODO: Add condition for integration tests to be passing
# - condition:

notifications:
- when: pull_request.opened
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: |
    Hey @{{ author }}, thanks for the PR! The review will start once
    the tests and CI checks have passed.
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: "The review is completed. Thanks @{{ author }}!"

groups:
  metadata-updates-major-minor:  # group name
    conditions:  # the group is activated when all of these statements are true
    - "'*travis*' in statuses.succeeded"
    - "base.ref == 'develop'"
    - "'major' in body or 'minor' in body" # major or minor change is indicated in body of PR
    - "'content' in labels"
    reviewers:  # people who can approve for this group
      users:
      - malloryfreeberg
      - malloryfreeberg
      - daniwelter
      - daniwelter
      - zperova
      - zperova
      - ESapenaVentura
      - ESapenaVentura
      - willrockout
      - cjvillar
    reviews:  # settings for approval and reviewer selection
      required: 2
      request_order: shuffle  # reviewers will be chosen in a random order

  metadata-updates-patch:
    conditions:
    - "'*travis*' in statuses.succeeded"
    - "base.ref == 'develop'"
    - "'patch' in body" # patch change is indicated in body of PR
    reviewers:
      users:
      - malloryfreeberg
      - malloryfreeberg
      - daniwelter
      - daniwelter
      - zperova
      - zperova
      - ESapenaVentura
      - ESapenaVentura
      - willrockout
      - cjvillar
    reviews:
      required: 1
      request_order: shuffle

# TODO: Add a code review group
#  code-review:

