version: 3

# The following line breaks the yml - 404 page not found error
# extends: https://api.github.com/repos/example/pullapprove-config/contents/.pullapprove.yml

# If this conditions are not met, it will throw the 'unmet_status'.
pullapprove_conditions:
- condition: "base.ref in ['integration', 'staging', 'master'] and labels in ['Security', 'release', 'hotfix']"
  unmet_status: failure
  explanation: "Only releases, hotfixes and security updates are allowed to merge to environments higher than develop"
- condition: "'on hold' not in labels"
  unmet_status: pending
  explanation: "PR review is on hold"
- condition: "'*travis*' in statuses.successful"
  unmet_status: failure
  explanation: "Travis CI tests must pass before review starts"

notifications:
- when: pull_request.opened
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: |
    Hey @{{ author }}, thanks for the PR! The review will start once
    the tests and CI checks have passed.
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'" # Only contributing authors get this message
  comment: "The review is completed. Thanks @{{ author }}!"
- when: pull_request.opened
  if: "'[Snyk]' in title"   # Notify Enrique to assign security label
  comment: "@ESapenaVentura please put the 'Security' label"
- when: pull_request.opened
  if: "'content' in labels and 'major' in body" # Notify the DCP for a major update
  comment: |
    Major metadata schema update, pinging @maniarathi @aaclan-ebi @MDunitz @NoopDog @brianraymor
    @jahilton @jychien @jlzamanian @samanehsan @hannes-ucsc @kislyuk . If No one objects, this will be merged on the
    following 5 working days.

groups:

  snyk-security-patches:
    conditions:
    - "'[Snyk]' in title"
    - "'Security' not in labels"
    reviewers:
      users:
      - ESapenaVentura
      - simonjupp
      - diekhans
      - willrockout
      - rolando-ebi
    reviews:
      required: 1
      request_order: shuffle

  metadata-updates-major-minor:  # group name
    conditions:  # the group is activated when all of these statements are true
    - "'*travis*' in statuses.succeeded"
    - "base.ref == 'develop'"
    - "'major' in body or 'minor' in body" # major or minor change is indicated in body of PR
    - "'content' in labels"
    reviewers:  # people who can approve for this group
      users:
      - zperova
      - mshadbolt
      - ESapenaVentura
      - zperova
      - mshadbolt
      - ESapenaVentura
      - willrockout
      - cjvillar
    reviews:  # settings for approval and reviewer selection
      required: 2
      request_order: shuffle  # reviewers will be chosen in a random order

  metadata-updates-patch:
    conditions:
    - "'*travis*' in statuses.succeeded"
    - "base.ref == 'develop'"
    - "'patch' in body" # patch change is indicated in body of PR
    - "'content' in labels"
    reviewers:
      users:
      - zperova
      - mshadbolt
      - ESapenaVentura
      - zperova
      - mshadbolt
      - ESapenaVentura
      - willrockout
      - cjvillar
    reviews:
      required: 1
      request_order: shuffle

  code-review:
    conditions:
    - "'*travis*' in statuses.succeeded"
    - "base.ref == 'develop'"
    - "'*.py' in files or '*.js' in files or '*.yml' in files"
    reviewers:
      users:
      - mshadbolt
      - ESapenaVentura
      - willrockout
      - cjvillar
    reviews:
      required: 1
      request_order: shuffle